#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with tmux
if test "$SSH_AUTH_SOCK" ; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

if [ -n "$DISPLAY" ]; then     # the DISPLAY variable is set
    if read proto cookie; then # proto and magic key waiting on STDIN
        if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
            xauth add unix:`echo $DISPLAY | cut -c11-` $proto $cookie
        fi
    fi
fi
