#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with tmux
if [ -e  "$SSH_AUTH_SOCK" ]
then
    ln -vsf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

if [ -n "$DISPLAY" ]; then     # the DISPLAY variable is set
    if read proto cookie; then # proto and magic key waiting on STDIN
        if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
            xauth add unix:`echo $DISPLAY | cut -c11-` $proto $cookie
        fi
    fi
fi

# SOURCES:
# https://unix.stackexchange.com/questions/178513/forwarding-x11-not-working-error-cant-open-display-localhost11-0
# https://apple.stackexchange.com/questions/48505/how-to-prevent-warnings-like-no-xauth-data-when-doing-ssh-from-os-x-to-other-mac
#
# vim: tw=0
